name: Android CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build APK with Gradle
      run: |
        chmod +x scripts/languagelist_updater.sh
        bash scripts/languagelist_updater.sh
      
        mkdir -p out
        chmod +x gradlew 
        
        # Build JRE JAR files (security manager, etc...)
        ./gradlew clean build
        # mkdir app_pojavlauncher/src/main/assets/components/internal_libs
        rm app_pojavlauncher/src/main/assets/components/lwjgl3/lwjgl-glfw-classes.jar
        cp jre_lwjgl3glfw/build/libs/jre_lwjgl3glfw-3.2.3.jar app_pojavlauncher/src/main/assets/components/lwjgl3/lwjgl-glfw-classes.jar
        
        # Build the launcher
        ./gradlew assembleDebug
        mv app_pojavlauncher/build/outputs/apk/debug/app_pojavlauncher-debug.apk out/app-debug.apk
        # mv app_pojavlauncher/build/intermediates/merged_native_libs/debug/out/lib out/debug_lib

    - name: Build APK without runtime
      run: | 
        rm -r app_pojavlauncher/src/main/assets/components/jre
        ./gradlew assembleDebug
        mv app_pojavlauncher/build/outputs/apk/debug/app_pojavlauncher-debug.apk out/app-debug-noruntime.apk

    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
          name: app-debug
          path: out/app-debug.apk

    - name: Upload APK (without runtime)
      uses: actions/upload-artifact@v2
      with:
          name: app-debug-noruntime
          path: out/app-debug-noruntime.apk

